### ISSUE TITLE
entropass extension is cutoff in firefox

### ISSUE THREAD

**Issue by magicbane** [clark800/entropass#2]
here's a snapshot of it: http://tinypic.com/r/2cenk07/8

**Comment by clark800** [comment]
Looks like the text boxes render bigger in your OS than in OSX. The fix is probably to add an explicit height to the popup.css file after line 19. I don't have an easy way to test this, would you be able to try it? http://stackoverflow.com/questions/1054570/is-it-possible-to-edit-modify-the-firefox-addons-after-installing

**Comment by magicbane** [comment]
I just tested it. I was able to tweak it to have it fit:
![Alt text](http://i59.tinypic.com/swr8g2.jpg)
It seems like there are other issues though:
![Alt text](http://i57.tinypic.com/2gt16iv.jpg)

I'll see if I can tweak around.

**Comment by clark800** [comment]
Cool thanks! If you do any more tweaking, just be sure to not change any of the existing CSS and only add "height" fields.

**Comment by clark800** [comment]
I tweaked the CSS a bit for version 3.0.0. Let me know if there are still any problems, thanks!
