### ISSUE TITLE
Chrome/firefox extensions incompatible

### ISSUE THREAD

**Issue by magicbane** [clark800/entropass#3]
I noticed that the chrome extension generates different hash from the firefox one when you get them from their respective marketplaces.
I haven't tried it when you build from source, so I'm not sure if it's just a version mismatch or a bug.

**Comment by clark800** [comment]
Yeah, it looks like there is a bug when a private key has not been set. Thanks for finding this. It seems that chrome and firefox match if you set the same private key. I'll continue investigating.

**Comment by magicbane** [comment]
Do you know which one the iOS is compatible to?  I don't have an apple device so I can't check.

**Comment by clark800** [comment]
I'm not sure because I use a private key, but I'm guessing the problem is in the Firefox extension in the reading of the private key. I'll probably look into it tomorrow.

**Comment by clark800** [comment]
Yes, the problem was in the firefox extension. If a private key was not set, it was passing `undefined` to the generatePassword function as the privateKeyHash, which then got casted to the string `"undefined"`. I fixed the issue and submitted a new version to Mozilla: https://addons.mozilla.org/en-US/firefox/addon/entropass/versions/?page=1#version-3.0.0
